# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - weown-frontend

on:
  push:
    branches:
      - deploy_test
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_61B797926B8F49B78B9E9D9AFC97FBFA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A55E984A595D47EDBE26112AC7E815DB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FA2F82C7F21A468383D758B58333E098 }}
      
      - name: Create .env file
        uses: SpicyPizza/create-envfile@v1
        with:
          CI: false
          file_name: .env

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'weown-frontend'
          slot-name: 'Production'
          package: build 